Repository OpenVoiceOS/ovos-plugin-manager, pull requests merged in 2022-03, with the labels that each got.

#35 Fix/stt config
  ovos_plugin_manager/stt.py
  ovos_plugin_manager/templates/stt.py
Labels: bug

#38 Fix/tx module reading
  ovos_plugin_manager/language.py
Labels: bug

#36 Implement `format_speak_tags` from neon_utils
  ovos_plugin_manager/templates/tts.py
  test/unittests/test_something.py
  test/unittests/test_ssml.py
Labels: enhancement

#40 fix/vad plugins
  ovos_plugin_manager/vad.py
Labels: bug

#41 Fix/lang plugs fallback
  ovos_plugin_manager/language.py
Labels: bug

#43 Misc fixes
  ovos_plugin_manager/skills.py
  ovos_plugin_manager/stt.py
  ovos_plugin_manager/templates/tts.py
  ovos_plugin_manager/vad.py
  ovos_plugin_manager/wakewords.py
Labels: bug

#44 Fix/phal config
  ovos_plugin_manager/templates/phal.py
Labels: bug

#45 Fix/multiple playback thread start
  ovos_plugin_manager/templates/tts.py
Labels: bug

#48 feat/segmentation_plugins
  ovos_plugin_manager/segmentation.py
  ovos_plugin_manager/templates/segmentation.py
  ovos_plugin_manager/utils/__init__.py
  requirements/requirements.txt
  setup.py
  test/unittests/test_split.py
Labels: enhancement

#49 Feat/improve segmentation
  ovos_plugin_manager/templates/segmentation.py
  ovos_plugin_manager/utils/__init__.py
  test/unittests/test_split.py
Labels: enhancement

#50 Feat/coref plugins
  ovos_plugin_manager/coreference.py
  ovos_plugin_manager/templates/coreference.py
  ovos_plugin_manager/utils/__init__.py
  test/unittests/test_coref.py
Labels: enhancement

#51 feat/tokenizer_plugin
  ovos_plugin_manager/segmentation.py
  ovos_plugin_manager/templates/segmentation.py
  ovos_plugin_manager/templates/tokenization.py
  ovos_plugin_manager/tokenization.py
  ovos_plugin_manager/utils/__init__.py
  setup.py
Labels: enhancement

#52 feat/postag_plugin
  ovos_plugin_manager/postag.py
  ovos_plugin_manager/templates/postag.py
  ovos_plugin_manager/templates/tokenization.py
  ovos_plugin_manager/utils/__init__.py
  setup.py
  test/unittests/test_tag.py
Labels: enhancement

#53 spans!
  ovos_plugin_manager/templates/postag.py
  test/unittests/test_tag.py
  test/unittests/test_tok.py
Labels: enhancement, refactor
