Repository OpenVoiceOS/ovos-plugin-manager, pull requests merged in 2022-02, with the labels that each got.

#24 fix/tts_config_reading
  ovos_plugin_manager/tts.py
Labels: bug

#25 fix/metrics_exceptions
  ovos_plugin_manager/templates/tts.py
Labels: bug

#6 PHAL
  ovos_plugin_manager/phal.py
  ovos_plugin_manager/templates/phal.py
  ovos_plugin_manager/utils/__init__.py
Labels: enhancement

#30 Fix/remove pyxdg
  ovos_plugin_manager/installation.py
  ovos_plugin_manager/utils/tts_cache.py
  requirements.txt
  setup.py
Labels: refactor

#28 refactor/bump_requests
  requirements.txt
  setup.py
Labels: refactor

#32 Backport/playback queue singleton
  ovos_plugin_manager/templates/tts.py
Labels: bug, refactor

#33 fix detach tts
  ovos_plugin_manager/templates/tts.py
  test/unittests/test_something.py
Labels: bug
