Repository OpenVoiceOS/ovos-plugin-manager, pull requests merged in 2023-06, with the labels that each got.

#162 Add error handling and tests to cache curation
  ovos_plugin_manager/g2p.py
  ovos_plugin_manager/utils/tts_cache.py
  test/unittests/test_tts.py
  test/unittests/test_utils.py
Labels: bug

#164 Automation fixes
  .github/workflows/propose_release.yml
  .github/workflows/publish_alpha.yml
Labels: bug, automations and tests

#167 feat/tts_session_context
  ovos_plugin_manager/templates/tts.py
  ovos_plugin_manager/utils/__init__.py
Labels: enhancement, refactor
