Repository OpenVoiceOS/ovos-plugin-manager, pull requests merged in 2023-10, with the labels that each got.

#179 feat/ovos_dialog_tts_transformers
  .gitignore
  ovos_plugin_manager/audio.py
  ovos_plugin_manager/audio_transformers.py
  ovos_plugin_manager/dialog_transformers.py
  ovos_plugin_manager/templates/audio.py
  ovos_plugin_manager/templates/phal.py
  ovos_plugin_manager/templates/transformers.py
  ovos_plugin_manager/templates/tts.py
  ovos_plugin_manager/utils/__init__.py
  test/unittests/test_utils.py
Labels: enhancement, refactor

#180 fix/playback_thread startup
  ovos_plugin_manager/templates/tts.py
Labels: bug

#181 fix/playback_thread startup
  ovos_plugin_manager/templates/tts.py
Labels: bug

#183 feat/translate_plug_as_arg
  ovos_plugin_manager/templates/solvers.py
Labels: enhancement

#185 Add license notice and link to plugins from neon_solvers package
  ovos_plugin_manager/templates/solvers.py
Labels: documentation

#184 Language Module Factory Tests/Fixes
  ovos_plugin_manager/language.py
  ovos_plugin_manager/utils/__init__.py
  ovos_plugin_manager/utils/config.py
  test/unittests/test_language.py
Labels: bug, automations and tests

#188 remove log spam
  ovos_plugin_manager/utils/__init__.py
  test/unittests/test_utils.py
Labels: bug

#190 Update test dependencies
  .github/workflows/unit_tests.yml
  requirements/test.txt
Labels: automations and tests

#187 Fix STT and TTS configuration handling
  ovos_plugin_manager/stt.py
  ovos_plugin_manager/tts.py
  ovos_plugin_manager/utils/config.py
  test/unittests/test_stt.py
  test/unittests/test_tts.py
  test/unittests/test_utils.py
Labels: bug
