Repository OpenVoiceOS/ovos-plugin-manager, pull requests merged in 2023-05, with the labels that each got.

#148 feat/more_solvers
  ovos_plugin_manager/solvers.py
  ovos_plugin_manager/templates/solvers.py
  ovos_plugin_manager/utils/__init__.py
  test/unittests/test_solver.py
Labels: enhancement

#149 refactor/solvers_init
  ovos_plugin_manager/templates/solvers.py
Labels: refactor

#150 fix/ww_json
  ovos_plugin_manager/wakewords.py
Labels: bug

#151 :tada: - GUI plugin
  ovos_plugin_manager/gui.py
  ovos_plugin_manager/templates/gui.py
  ovos_plugin_manager/utils/__init__.py
Labels: enhancement

#152 feat/microphone_plugs
  ovos_plugin_manager/microphone.py
  ovos_plugin_manager/templates/microphone.py
  ovos_plugin_manager/templates/stt.py
  ovos_plugin_manager/utils/__init__.py
Labels: enhancement

#153 Fix Hotword Plugin Load Compat
  ovos_plugin_manager/wakewords.py
  test/unittests/test_wakewords.py
Labels: bug

#154 Dinkum listener compat fixes with tests
  ovos_plugin_manager/templates/hotwords.py
  ovos_plugin_manager/templates/microphone.py
  test/unittests/templates/test_microphone_template.py
  test/unittests/test_microphone.py
Labels: enhancement

#159 Add persona plugins
  ovos_plugin_manager/persona.py
  ovos_plugin_manager/utils/__init__.py
  test/unittests/test_persona.py
  test/unittests/test_utils.py
Labels: enhancement

#160 Add trivial test case to `test_ocp`
  test/unittests/test_ocp.py
Labels: automations and tests
