Repository OpenVoiceOS/ovos-plugin-manager, pull requests merged in 2024-05, with the labels that each got.

#223 hotfix/voice_kwarg
  ovos_plugin_manager/templates/tts.py
  test/unittests/test_tts.py
Labels: bug

#225 Fix file path handling in setup.py
  setup.py
Labels: packaging

#226 refactor/legacy_audio
  ovos_plugin_manager/templates/audio.py
Labels: refactor

#227 fix/legacy_playlist_queue
  ovos_plugin_manager/templates/audio.py
Labels: bug

#230 fix/playback_time_not_abstract
  ovos_plugin_manager/templates/audio.py
Labels: bug

#231 fix/py3.12
  requirements/requirements.txt
Labels: packaging
